// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TECBank.Backend.Repository.DataContext;

#nullable disable

namespace TECBank.Backend.Migrations
{
    [DbContext(typeof(TecBankContext))]
    [Migration("20230422120510_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.16");

            modelBuilder.Entity("TECBank.Backend.Domains.Models.Conta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agencia")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ExcluidoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroConta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contas");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Agencia = 1,
                            CriadoEm = new DateTimeOffset(new DateTime(2023, 4, 22, 9, 5, 10, 229, DateTimeKind.Unspecified).AddTicks(3688), new TimeSpan(0, -3, 0, 0, 0)),
                            NumeroConta = "001",
                            Saldo = 0m,
                            SenhaHash = "$2a$12$RI.nqkMYyLAFOtPUEWXnCupCmzg68O5h0iw0P7bWGzR7eqR0mnkty"
                        },
                        new
                        {
                            Id = 2L,
                            Agencia = 1,
                            CriadoEm = new DateTimeOffset(new DateTime(2023, 4, 22, 9, 5, 10, 693, DateTimeKind.Unspecified).AddTicks(6200), new TimeSpan(0, -3, 0, 0, 0)),
                            NumeroConta = "002",
                            Saldo = 0m,
                            SenhaHash = "$2a$12$D13x6jEOHRNM9ZE8hrmgbO8niED2rclFwCJCSVpUj7YDNwsEVKXgW"
                        });
                });

            modelBuilder.Entity("TECBank.Backend.Domains.Models.Transacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<long>("ContaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ExcluidoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Historico")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoOperacao")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoTransacao")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContaId");

                    b.ToTable("Transacoes");
                });

            modelBuilder.Entity("TECBank.Backend.Domains.Models.Transacao", b =>
                {
                    b.HasOne("TECBank.Backend.Domains.Models.Conta", "Conta")
                        .WithMany("Transacao")
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conta");
                });

            modelBuilder.Entity("TECBank.Backend.Domains.Models.Conta", b =>
                {
                    b.Navigation("Transacao");
                });
#pragma warning restore 612, 618
        }
    }
}
